//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumables
    {
        public int ID { get; set; }
        public int Type_ID { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date_Added { get; set; }
    
        public virtual Consumable_Type Consumable_Type { get; set; }
    }
}
