//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Log
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Client_Service_ID { get; set; }
        public int Master_ID { get; set; }
        public string Payment_Type { get; set; }
        public decimal Material_Cost { get; set; }
        public string Note { get; set; }
    
        public virtual Client_Services Client_Services { get; set; }
        public virtual Masters Masters { get; set; }
    }
}
