//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID { get; set; }
        public int Master_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Service_ID { get; set; }
        public int Number_of_Services_Provided { get; set; }
        public decimal Material_Cost { get; set; }
        public decimal Master_Salary { get; set; }
        public decimal Salon_Revenue { get; set; }
    
        public virtual Masters Masters { get; set; }
        public virtual Services Services { get; set; }
    }
}
