//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaloonEntities : DbContext
    {
        public SaloonEntities()
            : base("name=SaloonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Services> Client_Services { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Consumable_Type> Consumable_Type { get; set; }
        public virtual DbSet<Consumables> Consumables { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Record_Log> Record_Log { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
